language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "redis & tests"
      before_script:
      # Forcing localhost in hosts file
      - sudo sed -i '1s/^/127.0.0.1 localhost\n/' /etc/hosts
      
      script: redis-server
      script: npm test
