language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "redis, mongod, tests"
      script: redis-server
      script: mongod
      script: npm test --detectOpenHandles
